### ISSUE TITLE
Proposal: make launch.json git friendly

### ISSUE THREAD

**Issue by joined72** [williamoberg/godot-dotnet-tools#2]
Simple replacing old "program" launch.json variable with the following one:

`"program": "${config:godot-dotnet-tools.executablePath}",`

will make launch.json git friendly! ;)

I hope this can help.

**Comment by williamoberg** [comment]
Good proposal! 
I'll try to implement this tomorrow 👍

**Comment by joined72** [comment]
Great, looking forward to seeing it in action! 👍

**Comment by williamoberg** [comment]
@joined72 
I did it straight away, lol.

It seems to work as expected! 
Thanks for the proposal, it simplifies the workflow quite a bit 👍 

Let me know if you have any issues with the new update!

**Comment by joined72** [comment]
Really, really, REALLY... GREAT! ;)
Works really very well! :)
