### ISSUE TITLE
Proposal: ask for the "Godot file path" at the Installation Time

### ISSUE THREAD

**Issue by joined72** [williamoberg/godot-dotnet-tools#4]
Why don't wait that the user edit the `settings.json/godot-dotnet-tools.executablePath` variable and ask him to select the Godot file path at the installation time using something like the following example?

```
// Show the file dialog
let fileUris = await vscode.window.showOpenDialog(canSelectFolders: false, canSelectFiles: true, canSelectMany: false, openLabel: 'Select Godot Executable File...');
if (fileUris && fileUris.length > 0) {
    // Get the first selected file path
    let filePath = fileUris[0].fsPath;
    // Store the file path in the user settings
    let config = vscode.workspace.getConfiguration('yourExtension');
    await config.update('filePath', filePath, vscode.ConfigurationTarget.Global);
}
```

**Comment by williamoberg** [comment]
Yes, again good proposal! 
Probably when generating files for the first time/when the path is not set, this should be done!

**Comment by williamoberg** [comment]
I'll see if i can do it tonight, otherwise I'll do it tomorrow!

**Comment by joined72** [comment]
> I'll see if i can do it tonight, otherwise I'll do it tomorrow!

Thanks a lot for your availability and great work! 👍

**Comment by williamoberg** [comment]
@joined72 
It's implemented now!

Now when generating the files and the path in the user settings is not valid (or empty), you get a file dialog to choose your executable. It then sets your config settings and generates the launch file (if it doesn't already exist) 👍 

I have only tested it on Windows so far, but I think it should work on mac and linux as well. 
As always, please let me know if it works for you and if you have any issues!

**Comment by joined72** [comment]
Great, I'll test on both Windows and Linux tomorrow on morning. I'll let you updated ASAP.  ;)

**Comment by williamoberg** [comment]
Cool, thanks!

**Comment by joined72** [comment]
Testes and works fine on both Windows and Linux with only a little issue on the Linux side, when try to select the Godot executable the file isn't showed (I suppose you use as filter *.exe that on Linux and MacOS doesn't works) and I must change the file type (from the dialog) from "Executable" to "All files".

**Comment by williamoberg** [comment]
Updated now!

**Comment by joined72** [comment]
Linux haven't a standard extension for executable files! :)
Great :)

**Comment by williamoberg** [comment]
Again, thanks for the help and the good suggestions!
Very much appreciated 🥇 

The extension feels alot more user friendly now I think.

**Comment by joined72** [comment]
> Again, thanks for the help and the good suggestions! Very much appreciated 🥇

I'm very happy to can help.
 
> The extension feels alot more user friendly now I think.

Yes, it is! :)
