### ISSUE TITLE
Sharing: make this wonderful extension known

### ISSUE THREAD

**Issue by joined72** [williamoberg/godot-dotnet-tools#5]
Just to let you know, I'm speaking of this extension on the Godot Reddit and on the Discord channel too, I think many C# developers will need it! ;)

This is the Reddit post (if you wish to comment) ;) ...
https://www.reddit.com/r/godot/comments/180e9q7/are_you_using_c_take_a_look_here_working_vscode/

**Comment by williamoberg** [comment]
Hehe thanks mate! Appreciate it :)
