### ISSUE TITLE
Problems with running on Linux

### ISSUE THREAD

**Issue by krisutofu** [williamoberg/godot-dotnet-tools#8]
On Linux (and probably) Mac, it does not simply work to enter the Godot application path as program name in `launch.json`. Instead, the debugger (or the C# debugger extension?) enforces a `dotnet-` prefix on the path when no `.exe` suffix was found. This means, when entering "godot" as "program" name, it will look for `dotnet-godot` in the PATH and subsequently, the Godot application requires a GodotSharp directory in its working directory (where it is called). Both can be linked to avoid copying the files over to a new location.

What I tested so far: it will not work to rename the Godot application to an .exe suffix. Because ultimately, it will fail with an BadImageFormatException-like Exception.
It runs when the `dotnet-godot` command is faked to point to the godot application but pausing and breakpoints won't work at all.

I really would like to know if anyone managed to make Godot 4+ C# debugging running on Linux and how.

**Comment by hxhieu** [comment]
@krisutofu 
Its working fine for me.
For convenient, I just symlink to Gotdot excutable like so
```
ln -s '/path/to/your/godot/Godot_v4.2.2-stable_mono_linux.x86_64' /usr/local/bin/godot
```
Then in the `settings.json`
```
{
  ...
  "godot-dotnet-tools.executablePath": "godot"
}
```
Make sure `/usr/local/bin` is in your `PATH`, or do an absolute path `/usr/local/bin/godot` on the above
When a new version of Godot comes out, we just need to relink

**Comment by krisutofu** [comment]
> @krisutofu Its working fine for me. For convenient, I just symlink to Gotdot excutable like so
> 
> ```
> ln -s '/path/to/your/godot/Godot_v4.2.2-stable_mono_linux.x86_64' /usr/local/bin/godot
> ```
> 
> Then in the `settings.json`
> 
> ```
> {
>   ...
>   "godot-dotnet-tools.executablePath": "godot"
> }
> ```
> 
> Make sure `/usr/local/bin` is in your `PATH`, or do an absolute path `/usr/local/bin/godot` on the above When a new version of Godot comes out, we just need to relink

Thank you for the reminder. I "fixed" the issue by using Microsoft's proprietary version of VSCode. I originally installed just any version which was the non-proprietary one.
